### ISSUE TITLE
Playback with looping

### ISSUE THREAD

**Issue by Dekalox** [Dude036/soundboard#1]
I've got your soundboard working, but am looking for a way to automatically stop playback after playing a file.
What changes would be necessary to implement this?

**Comment by Dude036** [comment]
Remove the repeat input argument from the VLC initialization from main.py file on line 10, and it should work as you'd like it to. Here's what Line 10 should look like for you.
`instance = vlc.Instance()`

**Comment by Dekalox** [comment]
Works like a charm, thank you!
